config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  resources :users
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_scope :user do
      get '/confirmation-getting-started' => 'users/registrations#getting_started',
          as: 'confirmation_getting_started'
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
    get 'persons/profile'
    get 'persons/profile', as: 'user_root'
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :events
    resources :categories do
      resources :subs
      resources :images do
        resources :comments
        resources :likes
      end
    end
    get 'images/upl_img'
    get 'comments/index'
    get 'images/index'
    root 'categories#index'
  end
end

app/models/admin_user.rb
# admin-user
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :encrypted_password, presence: true, length: { minimum: 6 }
  validates :email, presence: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# applicationrecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# category
class Category < ApplicationRecord
  has_many :images, dependent: :destroy
  has_many :subs, dependent: :destroy
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :users, through: :subs, dependent: :destroy
  accepts_nested_attributes_for :subs, allow_destroy: true
  validates :name, presence: true
  extend FriendlyId
  friendly_id :name, use: [:finders]
  def to_s
    self.name
  end

end

app/models/comment.rb
# comment
class Comment < ApplicationRecord
  belongs_to :image
  belongs_to :user
  validates :com_email, presence: true
  validates :body, presence: true
  def to_s
    self.id
  end
end

app/models/event.rb
# event
class Event < ApplicationRecord
  belongs_to :user
  def to_s
    self.id
  end
end

app/models/image.rb
# image
class Image < ApplicationRecord
  attr_accessor :img, :remote_img_url
  mount_uploader :img, ImgUploader
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :category
  validates :img, file_size: { less_than: 50.megabytes }, presence: true
  def to_s
    self.id
  end
end

app/models/like.rb
# like
class Like < ApplicationRecord
  belongs_to :image
  belongs_to :user
  validates :user, uniqueness: { scope: :image }
  def to_s
    self.id
  end
end

app/models/sub.rb
# sub
class Sub < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :user, uniqueness: { scope: :category }
  def to_s
    self.id
  end
end

app/models/user.rb
# user
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :lockable,
         :confirmable, :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable, omniauth_providers: [:twitter]
  # attr_accessor :cached_failed_attempts
  has_many :comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :subs
  has_many :categories_owner, class_name: 'Category', foreign_key: :user_id, dependent: :destroy
  has_many :categories, through: :subs, dependent: :destroy
  accepts_nested_attributes_for :categories, allow_destroy: true
  mount_uploader :avatar, AvatarUploader
  validates :email, presence: true
  validates :encrypted_password, presence: true, length: { minimum: 6 }
  def to_s
    self.email
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.skip_confirmation!
      user.email = auth.info.nickname + '@twitter.com'
      user.login = auth.info.nickname
      user.avatar = auth.info.image
      user.password = Devise.friendly_token[0, 20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.save
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.logins_before_captcha
    2
  end
end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer
end

app/controllers/comments_controller.rb
# this controller is responsible for the operation with comments
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :search_subs, only: [:create]

  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new(comment_params)
    @comment.save!
    action_t = ' Comment where id = ' + @comment.id.to_s + '
    and Image_id = ' + @image.id.to_s
    event_create(action_t)
    redirect_to category_image_path(@image.category_id, @image.id)
  end

  def index
    popular
    @categories = Category.all
    @categories_sub = current_user.categories
    @comments = Comment.all.page(params[:page]).per(8)
  end

  private

  def search_subs
    @categories_sub = current_user.categories
  end

  def comment_params
    params.require(:comment).permit(:com_email, :body, :user_id)
  end
end

app/controllers/likes_controller.rb
# this controller is responsible for the operation with likes
class LikesController < ApplicationController
  def create
    @image = Image.find(params[:image_id])
    @like = @image.likes.new(comment_params)
    @like.save!
    action_t = 'Like where id = ' + @like.id.to_s + '
    and Image_id = ' + @image.id.to_s
    event_create(action_t)
    redirect_to category_image_path(@image.category_id, @image.id)
  end

  def destroy
    @image = Image.find(params[:image_id])
    @like = @image.likes.find(params[:id])
    @like.destroy
    action_t = 'DisLike where id = ' + @like.id.to_s + '
    and Image_id = ' + @image.id.to_s
    event_create(action_t)
    redirect_to category_image_path(@image.category_id, @image.id)
  end

  private

  def comment_params
    params.require(:like).permit(:image_id, :user_id)
  end
end

app/controllers/subs_controller.rb
# this controller is responsible for the operation with subscribes
class SubsController < ApplicationController
  before_action :authenticate_user!
  def create
    @category = Category.friendly.find(params[:category_id])
    @sub = @category.subs.create(sub_params)
    @sub.save!
    action_t = ' Subscribe category where category_id = ' + @category.id.to_s
    event_create(action_t)
    sub_mail(@category)
    redirect_to @category
  end

  def destroy
    @category = Category.friendly.find(params[:category_id])
    @sub = @category.subs.find(params[:id])
    @sub.destroy
    action_t = ' Unsubscribe category where category_id = ' + @category.id.to_s
    event_create(action_t)
    redirect_to @category
  end

  private

  def sub_mail(category)
    if current_user.login.nil?
    else
      Resque.enqueue(SubMail, category.owner.id)
    end
  end

  def event_create(a_t)
    Event.create(user_id: current_user.id, action_type: a_t,
                 orig_url: request.original_url)
  end

  def sub_params
    params.require(:sub).permit(:user_id, :category_id)
  end
end

app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
# CallbacksHelper
module CallbacksHelper
end

app/helpers/categories_helper.rb
# CategoriesHelper
module CategoriesHelper
end

app/helpers/comments_helper.rb
# CommentsHelper
module CommentsHelper
end

app/helpers/events_helper.rb
# EventsHelper
module EventsHelper
end

app/helpers/images_helper.rb
# ImagesHelper
module ImagesHelper
end

app/helpers/likes_helper.rb
# LikesHelper
module LikesHelper
end

app/helpers/persons_helper.rb
# PersonsHelper
module PersonsHelper
end

app/helpers/subs_helper.rb
# SubsHelper
module SubsHelper
end

app/helpers/users_helper.rb
# UsersHelper
module UsersHelper
end

app/views/admin/comment/_create_comment.haml
- @doc.xpath('//img').each do |img|
  %img{src: "#{img['src']}"}
  = form_for :image, url:{controller: :comments, action: :create} do |form|
    = form.hidden_field :remote_img_url ,value: img['src']
    = form.select(:category_id, @category.all.collect {|a| [a.name, a.id]})
    = form.submit "Upload image" ,class: "btn btn-success btn-lg"
  %br
= link_to "Back", admin_parse_path,  class: "btn btn-danger btn-lg"

app/views/comments/_auth.html.haml
%div.auth
  - if user_signed_in?
    %span.u_name
      - if current_user.avatar.url.nil?
        = link_to image_tag(asset_path("no_avatar.jpg"), class: "avatar"), edit_user_registration_path
      - else
        = link_to image_tag(current_user.avatar.url, class: "avatar"), edit_user_registration_path
      %br
      %p.username
        - if current_user.login.nil?
          #{current_user.email}
        - else
          #{current_user.login}
      %br
  - else

    = link_to t(".enterauth"), new_user_session_path

    или #{link_to t(".reg"), new_user_registration_path}

app/views/comments/index.html.haml
%require_tree
%div.main
  %div.first
    = render "auth"
    %div.buttons
      .but5top
        = button_to t(".butcats"), categories_path,  class: "but5top",:method => :get, data_toggle: "tooltip", dataplacement: "bottom", title:"Gallery"
      .but5top
        = button_to t(".newcategory"), new_category_path,  class: "but5top",:method => :get
      %div.dropdown
        %button#dLabel2{"data-target" => "#", "data-toggle" => "dropdown",:href => "/page.html", :role => "button" , class: "but5top", data_toggle: "tooltip", dataplacement: "bottom", title:"List of categories"}
          %p.textconf
            = t(".topbutcat")
        %ul.dropdown-menu{"aria-labelledby" => "dLabel2", :role => "menu"}
          %div.top_cat
            - @out.each do |category|
              = button_to category.name, category_path(category),  class: "buttlist",:method => :get
      %div.dropdown
        %button#dLabel1{"data-target" => "#", "data-toggle" => "dropdown",:href => "/page.html", :role => "button" , class: "but5top", data_toggle: "tooltip", dataplacement: "bottom", title:"List of categories"}
          %p.textconf
            = t(".allbutcat")
        %ul.dropdown-menu{"aria-labelledby" => "dLabel2", :role => "menu"}
          %div.all_cat
            - @categories.each do |category|
              = button_to category.name, category_path(category),  class: "buttlist",:method => :get
      .but5top
        = button_to t(".butimgs"), images_index_path,  class: "but5top",:method => :get, data_toggle: "tooltip", dataplacement: "bottom", title:"Gallery"
      .but6top
        = button_to t(".butcomms"), comments_index_path,  class: "but6top",:method => :get, data_toggle: "tooltip", dataplacement: "bottom", title:"List of comments"
      - if @categories_sub.nil?
      - else
        %div.dropdown
          %button#dLabel3{"data-target" => "#", "data-toggle" => "dropdown",:href => "/page.html", :role => "button" , class: "but5top", data_toggle: "tooltip", dataplacement: "bottom", title:"List of categories"}
            %p.textconf
              = t(".subsbutcat")
          %ul.dropdown-menu{"aria-labelledby" => "dLabel3", :role => "menu"}
            %div.all_cat
              - @categories_sub.each do |category|
                = button_to category.name, category_path(category.id),  class: "buttlist",:method => :get
    %div.lang
      = link_to "Ru", {locale: :ru}, class: "buttlist", data_toggle: "tooltip", dataplacement: "bottom", title:"change language to Russian", :id => "loc_ru"
      = link_to "En", {locale: :en}, class: "buttlist", data_toggle: "tooltip", dataplacement: "bottom", title:"change language to English", :id => "loc_en"
    %br


  %div.second

    - @comments.each do |comm|
      %div.com_index
        .panel.panel-primary
          .panel-heading
            - if comm.user.avatar.url.nil?
              = image_tag("no_avatar.jpg", class: "commavatar")
            - else
              = image_tag(comm.user.avatar.url, class: "commavatar")
            - if comm.user.login.nil?
              = comm.user.email
            - else
              = comm.user.login
            = link_to t(".toimg"), category_image_path(comm.image.category_id,comm.image),{class: "btn btn-primary btn-lg", id: "pic"} unless comm.image.img.blank?
          .panel.panel-default
            .panel-heading
              = comm.com_email
            .panel-heading
              = comm.body
    = paginate @comments